Create lesson: Inscribed Rectangle Problem
3b1b/3Blue1Brown.com pull request #68
Opened 2021-06-05 03:34 UTC by PullJosh

2021-06-05 03:40 UTC, PullJosh commented
Preview link: https://deploy-preview-68--3blue1brown.netlify.app/lessons/inscribed-rectangle-problem/

2021-06-07 21:30 UTC, 3b1b requested changes

2021-06-07 21:30 UTC, 3b1b commented on content/lessons/2016/inscribed-rectangle-problem/index.md
> +**Answer:** {{< spoiler >}}Convert each loop point to a number between 0 and 1, and then use those two numbers as the x and y coordinates in the square.{{< /spoiler >}}
```suggestion
**Answer:** {{< spoiler >}} This assumes you've already chosen a _parameterization_ of the loop, meaning a continuous way to associate individual points with numbers between 0 and 1. From there, consider the numbers associated with the two points as the x and y coordinates in the square.{{< /spoiler >}}
```

2021-06-07 21:30 UTC, 3b1b commented on content/lessons/2016/inscribed-rectangle-problem/index.md
> +If you bend this square to perform the gluing, first rolling it into a cylinder to glue the left and right edges, then gluing the ends of the cylinder, which represent the top and bottom edges, we ge
```suggestion
If you bend this square to perform the gluing, first rolling it into a cylinder to glue the left and right edges, then gluing the ends of the cylinder, which represent the top and bottom edges, we get a torus, the surface of a doughnut.
```

2021-06-07 21:30 UTC, 3b1b commented on content/lessons/2016/inscribed-rectangle-problem/index.md
> +There is a unique correspondence between pairs of points on the loop and individual points on the torus.
Combine this image with the one below it, making this image the top of the next one.

2021-06-07 21:30 UTC, 3b1b commented on content/lessons/2016/inscribed-rectangle-problem/index.md
> +{{< figure image="fold-square.png" video="fold-square.mov" >}}
Again, for some reason, this clip does not show for me.  I wonder if it has anything to do with using .mov instead of .mp4?  It shouldn't...

2021-06-07 21:30 UTC, 3b1b commented on content/lessons/2016/inscribed-rectangle-problem/index.md
> +{{< figure video="map-strip-to-surface.mov" >}}
Again, this doesn't play for me.

2021-06-07 21:30 UTC, 3b1b commented on content/lessons/2016/inscribed-rectangle-problem/index.md
> +{{< figure image="sudanese-mobius-band.png" >}}
We may also want to link to this, which makes the whole thing a lot clearer, to me at least.  (Still confusing, but not _as_ confusing).

https://vimeo.com/286360639

2021-06-07 21:30 UTC, 3b1b commented on content/lessons/2016/inscribed-rectangle-problem/index.md
> +It turns out that gluing the edge of a Möbius strip to the edge of a disk gives us a surface which is topologically equivalent to something called the "real projective plane". So the surface we defin
```suggestion
It turns out that gluing the edge of a Möbius strip to the edge of a disk gives us a surface which is topologically equivalent to something called the "real projective plane". So the surface we defined above for the inscribed rectangle problem, combined with the interior of the closed loop on the plane which it hugs, might be described by a mathematician as an embedding of the real projective plane into 3D space. And as you may have guessed, those mathematicians are a clever bunch, and they proved that you can’t have such an embedding. That is to say, trying to jam this surface into 3D space forces it to intersect itself.
```

2021-06-07 21:30 UTC, 3b1b commented on content/lessons/2016/inscribed-rectangle-problem/index.md
> +The proof is, as the lazy author loves to write, beyond the scope of this article. But perhaps by now you have an appreciation for why we’d ever care.
```suggestion
If you're itching to understand _why_ this is true, wonderful! Consider this an excuse to start digging more into topology. Facts about which surfaces are topologically distinct from others, and how many dimensions they can live in, can be surprisingly hard to formalize and prove. But if you understand this proof sketch to the inscribed rectangle problem, you'll understand how these kinds of facts are more than mere idle ponderings.
```

2021-06-11 12:46 UTC, PullJosh commented on content/lessons/2016/inscribed-rectangle-problem/index.md
> +{{< tweet 1390169453346787329 >}}
The tweet component just comes built-in to Hugo, so I say we don't worry about it for now.

2021-06-11 13:28 UTC, PullJosh commented
Okay, I made the suggested changes and replaced `.mov` files with `.mp4`. Can you check to see if the new video files are working for you?

Then I think we're set to merge.

2021-06-15 18:46 UTC, 3b1b commented
Looks good to me. Do you mind resolving the conflict then merging?

2021-06-15 18:58 UTC, PullJosh commented
This lesson was built for Hugo, and I don't really have the git savvy to handle all those conflicts, so I might just close this and create new branch & PR based on the Next version of the site. Unless you know of an easy way to keep using this one!

2021-06-15 19:00 UTC, 3b1b commented
Sure, whatever is easiest.

2021-06-15 23:07 UTC, PullJosh commented
Closed in favor of #87

2021-06-15 23:07 UTC, closed without merging